Marcom_Application/Marcom_Application/Controllers/T_SouvenirController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Marcom_Application.Model;
using Marcom_Application.Repo;
using Marcom_Application.ViewModel;
using PagedList;

namespace Marcom_Application.Controllers
{
    public class T_SouvenirController : Controller
    {
        // GET: T_Souvenir
        public static string DataKosong;
        public ActionResult Index(string searchTransactionCode, string searchReceivedby, DateTime? searchReceivedDate , DateTime? searchCreatedDate, int? searchCreatedby, int? page)
        {
            List<transaksi_souvenir> ListT_Souvenir = T_SouvenirRepo.GetAllData();
            ViewBag.CurrentFilter1 = searchTransactionCode;
            ViewBag.CurrentFilter2 = searchReceivedby;
            ViewBag.CurrentFilter3 = searchReceivedDate;
            ViewBag.CurrentFilter4 = searchCreatedDate;
            ViewBag.CurrentFilter5 = searchCreatedby;
            ViewBag.DataKosong = DataKosong;
            if (!string.IsNullOrEmpty(searchTransactionCode))
            {
                ListT_Souvenir = ListT_Souvenir.Where(x => x.code == searchTransactionCode).ToList();
            }
            if (!string.IsNullOrEmpty(searchReceivedby))
            {
                ListT_Souvenir = ListT_Souvenir.Where(x => x.received_by == searchReceivedby).ToList();
            }
            if (searchReceivedDate != null)
            {
                ListT_Souvenir = ListT_Souvenir.Where(x => x.received_date == searchReceivedDate).ToList();
            }
            if (searchCreatedDate != null)
            {
                ListT_Souvenir = ListT_Souvenir.Where(x => x.created_date.Value.ToString("dd MMMM yyyy") == searchCreatedDate.Value.ToString("dd MMMM yyyy")).ToList();
            }
            if (searchCreatedby != null)
            {
                ListT_Souvenir = ListT_Souvenir.Where(x => x.created_by == searchCreatedby).ToList();
            }
            if (ListT_Souvenir.Count == 0)
            {
                DataKosong = "Data tidak ditemukan";
            }
            else
            {
                DataKosong = "";
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(ListT_Souvenir.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateData()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Edit()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UpdateData()
        {
            return View();
        }
        [HttpGet]
        public ActionResult View_T_Souvenir()
        {
            return View();
        }
    }
}

Marcom_Application/Marcom_Application/Views/T_Souvenir/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

Marcom_Application/Marcom_Application/Views/T_Souvenir/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

Marcom_Application/Marcom_Application/Views/T_Souvenir/Index.cshtml
@model PagedList.IPagedList<Marcom_Application.Model.transaksi_souvenir>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    int no = 1;
}
<br />
<div class="row col-lg-12" style="width:93%">
    <div class="alert alert-info cls_alert"></div>
</div>
<div class="panel panel-primary" style="width:90%">
    <div class="panel-heading">List Transaction Souvenir</div>
    <div class="panel-body">
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("Transaction", "Index", "T_Souvenir")</li>
            <li class="active">List Transaction Souvenir</li>
        </ol>
        <button class="btn btn-primary cls_add" id="btn_add" style="margin-left:87%">Add</button>
        @using (Html.BeginForm("Index", "T_Souvenir", FormMethod.Get, new { @id = "form_create" }))
        {
            <br />
            <div class="row" style="margin-left:0%">
                <div class="col-sm-2" style="padding-right:1px;padding-left:5px;">
                    @Html.TextBox("searchTransactionCode", ViewBag.CurrentFilter1 as string, new { @class = "form-control", @style = "width:100%;", @placeholder = "Transaction Code" })
                </div>
                <div class="col-md-2" style="padding-right:1px;padding-left:5px;">
                    @Html.TextBox("searchReceivedby", ViewBag.CurrentFilter2 as string, new { @class = "form-control", @style = "width:100%;", @placeholder = "Received By" })
                </div>
                <div class="col-md-2" style="padding-right:1px;padding-left:5px;">
                    @Html.TextBox("searchReceivedDate", ViewBag.CurrentFilter3 as string, new { @class = "form-control", @style = "width:100%;", @placeholder = "Received Date", @type = "date" })
                </div>
                <div class="col-sm-2" style="padding-right:0px;padding-left:5px;">
                    @Html.TextBox("searchCreatedDate", ViewBag.CurrentFilter4 as string, new { @class = "form-control", @style = "width:100%;", @placeholder = "Created ", @type = "date" })
                </div>

                <div class="col-sm-2" style="padding-right:0px;padding-left:5px;">
                    @Html.TextBox("searchCreatedby", ViewBag.CurrentFilter5 as string, new { @class = "form-control", @style = "width:100%;", @placeholder = "Created By" })
                </div>
                <div class="col-md-2" style="padding-left:5px">
                    <button class=" btn btn-warning cls_search" id="btn_search">Search</button>
                </div>
            </div>
        }

        <hr />
        <table class="table table-striped">
            <tbody>
                <tr>
                    <th>No</th>
                    <th>Transaction Code</th>
                    <th>Received By</th>
                    <th>Received Date</th>
                    <th>Created Date</th>
                    <th>Created By</th>
                    <th>Action</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@no</td>
                        <td>@item.code</td>
                        <td>@item.received_by</td>
                        <td>@item.received_date</td>
                        <td>@item.created_date.Value.ToString("dd/MM/yyyy")</td>
                        <td>@item.created_by</td>

                        <td>
                            <span class="glyphicon glyphicon-search cls_view" id_t_souvenir="@item.id" data_code="@item.code"></span>
                            <span class="glyphicon glyphicon-pencil cls_edit" id_t_souvenir="@item.id" data_code="@item.code"></span>
                            <span class="glyphicon glyphicon-trash cls_delete" id_t_souvenir="@item.id"></span>
                        </td>
                    </tr>
                    no++;
                }
            </tbody>
        </table>
        <div style="text-align: center; font-size: large; color: #007bff">@ViewBag.DataKosong</div>
        <!--untuk pagination-->
        @*<p style="float:right">
               Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
            </p>*@
        <div class="row" style="float:right;padding-right:1em;">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="width:80%;padding-bottom:10%;" id="modal_dialog_id">
        <div class="modal-content">
            <div class="modal-header" id="modal_header_id">
                <h5 class="modal-title" id="exampleModalLabel">  </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal_body_id"></div>
            <div class="modal-footer" id="modal_footer_id" style="display:none;">
                <button type="button" id="id_btn_delete" class="btn btn-primary">Delete</button>
                <button type="button" class="btn  btn-warning cls_cancel" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

Marcom_Application/Marcom_Application/Views/T_Souvenir/View_T_Souvenir.cshtml
@{
    ViewBag.Title = "View_T_Souvenir";
}

<h2>View_T_Souvenir</h2>