Marcom_Application/Marcom_Application/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Marcom_Application.Model;
using Marcom_Application.Repo;
using Marcom_Application.ViewModel;

namespace Marcom_Application.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }
    }
}

Marcom_Application/Marcom_Application/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Marcom_Application.Model;
using Marcom_Application.Repo;
using PagedList;
namespace Marcom_Application.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public static string DataKosong;
        public ActionResult Index(string searchCode, string searchName, string searchDescription, DateTime? searchDate, string searchCreatedby, int? page)
        {
            List<master_product> ListProduct = ProductRepo.GetAllData();
            ViewBag.CurrentFilter1 = searchCode;
            ViewBag.CurrentFilter2 = searchName;
            ViewBag.CurrentFilter3 = searchDescription;
            ViewBag.CurrentFilter4 = searchDate;
            ViewBag.CurrentFilter5 = searchCreatedby;
            ViewBag.DataKosong = DataKosong;
            if (!string.IsNullOrEmpty(searchName))
            {
                ListProduct = ListProduct.Where(x => x.name == searchName).ToList();
            }
            if (!string.IsNullOrEmpty(searchCode))
            {
                ListProduct = ListProduct.Where(x => x.code == searchCode).ToList();
            }
            if (!string.IsNullOrEmpty(searchDescription))
            {
                ListProduct = ListProduct.Where(x => x.description == searchDescription).ToList();
            }
            if (searchDate != null)
            {
                ListProduct = ListProduct.Where(x => x.created_date.ToString("dd MMMM yyyy") == searchDate.Value.ToString("dd MMMM yyyy")).ToList();
            }
            if (!string.IsNullOrEmpty(searchCreatedby))
            {
                ListProduct = ListProduct.Where(x => x.created_by == searchCreatedby).ToList();
            }
            if (ListProduct.Count == 0)
            {
                DataKosong = "Data tidak ditemukan";
            }
            else
            {
                DataKosong = "";
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(ListProduct.ToPagedList(pageNumber, pageSize));
            //return View(ListProduct);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateData(master_product dataproduct)
        {
            string result = ProductRepo.CreateData(dataproduct);
            string[] spearator = { "Berhasil" };
            return Json(new { respon = result.Split(spearator, StringSplitOptions.RemoveEmptyEntries) }, JsonRequestBehavior.AllowGet);
            //return Json(new { respon = result }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            master_product dataproduct = ProductRepo.GetDataById(id);
            return View(dataproduct);
        }
        [HttpPost]
        public ActionResult UpdateData(master_product dataproduct)
        {
            string result = ProductRepo.UpdateData(dataproduct);
            return Json(new { respon = result }, JsonRequestBehavior.AllowGet);

        }
        public ActionResult Delete(int id)
        {
            string result = ProductRepo.DeleteData(id);
            string[] spearator = { "Berhasil" };
            return Json(new { respon = result.Split(spearator, StringSplitOptions.RemoveEmptyEntries) }, JsonRequestBehavior.AllowGet);
            //return Json(new { respon = result }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult View(int id)
        {
            master_product dataview = ProductRepo.GetDataById(id);
            return View(dataview);
        }
        //cek name sama 
        public JsonResult CheckName(string name)
        {
            return Json(ProductRepo.GetDataNama(name), JsonRequestBehavior.AllowGet);
        }

    }
}

Marcom_Application/Marcom_Application/Controllers/T_EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Marcom_Application.Model;
using Marcom_Application.ViewModel;
using Marcom_Application.Repo;
using PagedList;
namespace Marcom_Application.Controllers
{
    public class T_EventController : Controller
    {
        // GET: T_Event
        public static string DataKosong;
        public ActionResult Index(int? status, string searchCode, string searchRequestBy, DateTime? searchRequestDate, string searchCreatedby,DateTime? searchCreatedDate, int? page)
        {
            //ViewBag.ListData
            List<transaksi_event> ListEvent = EventRepo.GetAllData();
            ViewBag.CurrentFilter1 = searchCode;
            ViewBag.CurrentFilter2 = searchRequestBy;
            ViewBag.CurrentFilter3 = searchRequestDate;
            ViewBag.CurrentFilter4 = status;
            ViewBag.CurrentFilter5 = searchCreatedby;
            ViewBag.CurrentFilter6 = searchCreatedDate;
            ViewBag.DataKosong = DataKosong;
            if (!string.IsNullOrEmpty(searchCode))
            {
                ListEvent = ListEvent.Where(x => x.code == searchCode).ToList();
            }
            if (!string.IsNullOrEmpty(searchRequestBy))
            {
                ListEvent = ListEvent.Where(x => x.request_by == searchRequestBy).ToList();
            }
            if (searchRequestDate != null)
            {
                ListEvent = ListEvent.Where(x => x.request_date.ToString("dd MMMM yyyy") == searchRequestDate.Value.ToString("dd MMMM yyyy")).ToList();
            }
            if (status != null)
              {
                  ListEvent = ListEvent.Where(x => x.status == status).ToList();
              }
            if (searchCreatedDate != null)
            {
                ListEvent = ListEvent.Where(x => x.created_date.Value.ToString("dd MMMM yyyy") == searchCreatedDate.Value.ToString("dd MMMM yyyy")).ToList();
            }
            if (!string.IsNullOrEmpty(searchCreatedby))
            {
                ListEvent = ListEvent.Where(x => x.created_by == searchCreatedby).ToList();
            }
            if (ListEvent.Count == 0)
            {
                DataKosong = "Data tidak ditemukan";
            }
            else
            {
                DataKosong = "";
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(ListEvent.ToPagedList(pageNumber, pageSize));
           
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateData(VMEvent dataevent)
        {
            string result = EventRepo.CreateData(dataevent);
            string[] spearator = { "Berhasil" };
            return Json(new { respon = result.Split(spearator, StringSplitOptions.RemoveEmptyEntries) }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            VMEvent dataevent = EventRepo.GetDataById(id);
            return View(dataevent);
        }
        [HttpPost]
        public ActionResult UpdateData(VMEvent dataevent)
        {
            string result = EventRepo.UpdateData(dataevent);
            string[] spearator = { "Berhasil" };
            return Json(new { respon = result.Split(spearator, StringSplitOptions.RemoveEmptyEntries) }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult Approval(int id)
        {
            VMEvent dataevent = EventRepo.GetDataById(id);
            return View(dataevent);
        }
        [HttpPost]
        public ActionResult UpdateApproval(VMEvent dataevent)
        {
            string result = EventRepo.UpdateApproval(dataevent);
            string[] spearator = { "Berhasil" };
            return Json(new { respon = result.Split(spearator, StringSplitOptions.RemoveEmptyEntries) }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult CloseRequest(int id)
        {
            VMEvent dataevent = EventRepo.GetDataById(id);
            return View(dataevent);
        }
        public ActionResult UpdateClose(VMEvent dataevent)
        {
            string result = EventRepo.UpdateClose(dataevent);
            string[] spearator = { "Berhasil" };
            return Json(new { respon = result.Split(spearator, StringSplitOptions.RemoveEmptyEntries) }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult View(int id)
        {
                 
            VMEvent dataevent = EventRepo.GetDataById(id);
            return View(dataevent);
        }
        //public ActionResult GetDataById(long id)
        //{
        //    transaksi_event data = new transaksi_event();
        //    using (db_marcomEntities db = new db_marcomEntities())
        //    {
        //        data = db.transaksi_event.Where(a => a.id == id).FirstOrDefault();
        //    }

        //    return Json(new { respon = data }, JsonRequestBehavior.AllowGet);

        //}
        //tesss
        public ActionResult Delete(VMEvent dataevent)
        {
            string result = EventRepo.DeleteData(dataevent);
            return Json(new { respon = result }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetDataById(long id)
        {
            transaksi_event data = new transaksi_event();
            using (db_marcomEntities db = new db_marcomEntities())
            {
                data = db.transaksi_event.Where(a => a.id == id).FirstOrDefault();
            }

            return Json(new { respon = data }, JsonRequestBehavior.AllowGet);

        }
    }
}

Marcom_Application/Marcom_Application/Controllers/UnitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Marcom_Application.Model;
using Marcom_Application.Repo;
using PagedList;
namespace Marcom_Application.Controllers
{
    public class UnitController : Controller
    {
        // GET: Unit
        public static string DataKosong;
        public ActionResult Index(string UnitCode, string UnitName, string searchName, string searchCode, DateTime? searchDate, string searchCreatedUnit, int? page)
        {

            List<master_unit> ListUnit = new List<master_unit>();
            ListUnit = UnitRepo.GetAllData();
            ViewBag.name = UnitName;
            ViewBag.UnitCode = new SelectList(ListUnit, "code", "code", UnitCode);
            ViewBag.UnitName = new SelectList(ListUnit, "name", "name", UnitName);
            ViewBag.CurrentFilter1 = searchDate;
            ViewBag.CurrentFilter2 = searchCreatedUnit;
            ViewBag.DataKosong = DataKosong;
            if (!string.IsNullOrEmpty(searchName))
            {
                ListUnit = ListUnit.Where(x => x.name == searchName).ToList();
            }
            if (!string.IsNullOrEmpty(searchCode))
            {
                ListUnit = ListUnit.Where(x => x.code == searchCode).ToList();
            }
            if (searchDate != null)
            {
                ListUnit = ListUnit.Where(x => x.created_date.ToString("dd MMMM yyyy") == searchDate.Value.ToString("dd MMMM yyyy")).ToList();
            }
            if (!string.IsNullOrEmpty(searchCreatedUnit))
            {
                ListUnit = ListUnit.Where(x => x.created_by == searchCreatedUnit).ToList();
            }
            if (ListUnit.Count == 0)
            {
                DataKosong = "Data tidak ditemukan";
            }
            else
            {
                DataKosong = "";
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(ListUnit.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(master_unit dataunit)
        {
            string result = UnitRepo.CreateData(dataunit);
            string[] spearator = { "Berhasil" };
            return Json(new { respon = result.Split(spearator, StringSplitOptions.RemoveEmptyEntries) }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            master_unit dataunit = UnitRepo.GetDataById(id);
            ViewBag.name = dataunit.name;
            return View(dataunit);
        }
        [HttpPost]
        public ActionResult UpdateData(master_unit dataunit)
        {
            string result = UnitRepo.UpdateData(dataunit);
            return Json(new { respon = result }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int id)
        {
            string result = UnitRepo.DeleteData(id);
            string[] spearator = { "Berhasil" };
            return Json(new { respon = result.Split(spearator, StringSplitOptions.RemoveEmptyEntries) }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult View(int id)
        {
            master_unit dataview = UnitRepo.GetDataById(id);
            return View(dataview);
        }
        public ActionResult GetDataById(int id)
        {
            master_unit data = new master_unit();
            using (db_marcomEntities db = new db_marcomEntities())
            {
                data = db.master_unit.Where(a => a.id == id).FirstOrDefault();
            }

            return Json(new { respon = data }, JsonRequestBehavior.AllowGet);
        }
        //cek name sama 
        public JsonResult CheckName(string name)
        {
            return Json(UnitRepo.GetDataNama(name), JsonRequestBehavior.AllowGet);
        }

    }
}

Marcom_Application/Marcom_Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Marcom Application</title>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
   
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Content/swal.js"></script>

    <script src="~/Scripts/sweetalert.min.js"></script>
    @*<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>*@
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" style="color:white">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Marcom Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">                   
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Master <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Master_Product", "Index", "Product")</li>
                            <li>@Html.ActionLink("Master_Unit", "Index", "Unit")</li>
                            <li>@Html.ActionLink("Master_Souvenir", "Index", "Souvenir")</li> 
                            <li class="disabled">@Html.ActionLink("Master_Employee", "Index", "Employee")</li>
                            <li class="disabled">@Html.ActionLink("Master_Company", "Index", "Company")</li>
                            <li class="disabled">@Html.ActionLink("Master_Role", "Index", "Role")</li>
                            <li class="disabled">@Html.ActionLink("Master_User", "Index", "User")</li>
                            <li class="disabled">@Html.ActionLink("Master_Menu", "Index", "Menu")</li>
                            <li class="disabled">@Html.ActionLink("Master_Menu_Access", "Index", "Menu_Access")</li>
                                             
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Transaksi <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Transaksi_Event", "Index", "T_Event")</li>
                            <li>@Html.ActionLink("Transaksi_Souvenir", "Index", "T_Souvenir")</li>
                            <li class="disabled">@Html.ActionLink("Transaksi_Souvenir_Item", "Index", "T_Souvenir_Item")</li>
                            <li class="disabled">@Html.ActionLink("Transaksi_Design", "Index", "T_Design")</li>
                            <li class="disabled">@Html.ActionLink("Transaksi_Design_Item", "Index", "T_Design_Item")</li>
                            <li class="disabled">@Html.ActionLink("Transaksi_Design_Item_Film", "Index", "T_Design_Item_Film")</li>
                            <li class="disabled">@Html.ActionLink("Transaksi_Promotion", "Index", "T_Promotion")</li>
                            <li class="disabled">@Html.ActionLink("Transaksi_Promotion_Item", "Index", "T_Promotion_Item")</li>
                            <li class="disabled">@Html.ActionLink("Transaksi_Promotion_Item_File", "Index", "T_Promotion_Item_File")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Marcom Application By Dian Maulida</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)*@
</body>
</html>